### ISSUE TITLE
Can't create new Avalonia solution

### ISSUE THREAD

**Issue by canine-afficionado** [ForNeVeR/AvaloniaRider#163]
Hello, thanks for your hard work on this plugin.

I'm on rider 2021.2.2 / macOS 10.15.7 / plugin 1.0.0.1429607721 / .NET Core 6.0.100 / Avalonia.Templates 0.10.10

I don't have any avalonia options appearing in the rider new solution window

Thanks.

**Comment by LilPidgey** [comment]
Make sure to install the templates.
If that does not work go ahead and Click `More Templates`, from there install the Avalonia nupkg from 
`C:\Users\{User}\.templateengine\packages\Avalonia.Templates.0.10.10.nupkg`

This is how I got mine to work.

**Comment by canine-afficionado** [comment]
Had the templates installed but your workaround fixed it thanks.

Probably should leave this issue open however as it should work without having to install the templates manually in rider.

**Comment by ForNeVeR** [comment]
As of now, I have no plans to embed the project templates. You better get them from the official source and update them separately. If you have them installed and they don't show up in Rider, then it's a Rider issue, and not a plugin one. So, please open an issue in the Rider issue tracker.

(Also, I've checked and it works for me; it _should_ work.)

Avalonia releases pretty often, and I don't want my users to be stuck on some older version of NuGet packages just because I'm not able to release a new version of the plugin in a timely manner.

I'm not saying this decision is cast in stone, but for now I think so.
