### ISSUE TITLE
Security issue

### ISSUE THREAD

**Issue by AlexanderDotH** [ForNeVeR/AvaloniaRider#233]
It is possible to run any code on you system only by opening the project and open the .axaml file in the previewer.

This happens because the plugin runs the program and shows the ui in a frame. It should only read and interpret the .axaml file.

How to reproduce:
1. Clone the following repo: https://github.com/AlexanderDotH/POC.git
2. Open the "MainWindow.xaml" file and show it with the previewer
3. The calculator should open

![grafik](https://user-images.githubusercontent.com/20642291/197412886-38efdddd-d2d8-45b0-b800-4b9f54956730.png)

**Comment by ForNeVeR** [comment]
It is also possible to execute any code in the system by just opening a solution in any IDE.

The security dialog for first opening the solution is there for a reason. AvaloniaRider's trust model is the same as in Rider itself: there are trusted solutions (and trusted locations on disk), and everything else is distrusted by default. [See this article](https://www.jetbrains.com/help/rider/Settings_Trusted_Locations.html) for more information.

_(I should note that Visual Studio also has a similar trust model for code downloaded from the Internet.)_

If you have any examples of the plugin executing code bypassing the IDE's trust dialog, then please share them privately. Otherwise, I consider this as a non-issue, since the user _has_ to go mark the project as trusted before plugin will start working with it.
