### ISSUE TITLE
Adding Click event to a button in axaml file disables preview update

### ISSUE THREAD

**Issue by JenyaRostov** [ForNeVeR/AvaloniaRider#257]
**Describe the bug**
After adding Click event to any button live preview update in rider disables (no further updates whatsoever)

**To Reproduce**

Create a new cross-platform application (avalonia.xplat)
Add <Button> and a Click event to it
Live preview no longer updates

**Expected behavior**
I expect preview to update

**Screenshots**

Before adding click
![](https://i.imgur.com/RDbV596.png)

After adding click event
![](https://i.imgur.com/P1Wr3lC.png) 

**Desktop (please complete the following information):**

Windows 10
Rider 2022.3.1
AvaloniaRider 1.0.2
Avalonia 11.0.0-preview

I didn't notice this issue before so i'm open to suggestions why this might have happened

**Comment by ForNeVeR** [comment]
Check the logs from the previewer process, do they contain any errors?

**Comment by JenyaRostov** [comment]
Yes they do, but they always has this error
```
Sending StartDesignerSessionMessage
System.IO.EndOfStreamException: Attempted to read past the end of the stream.
   at Avalonia.Remote.Protocol.BsonStreamTransportConnection.ReadExact(Byte[] buffer) in /_/src/Avalonia.Remote.Protocol/BsonStreamTransport.cs:line 59
   at Avalonia.Remote.Protocol.BsonStreamTransportConnection.Reader() in /_/src/Avalonia.Remote.Protocol/BsonStreamTransport.cs:line 71
   ```

**Comment by ForNeVeR** [comment]
This means that a socket connection was terminated, perhaps by the IDE process. Are there any error messages from the IDE? In the IDE logs, perhaps?

**Comment by ForNeVeR** [comment]
I would guess that the compiled assembly doesn't contain the method in question, and that's why the previewer breaks (it cannot resolve a method and thus trying to resolve a property with a string parameter, which also fails).

Anyway, this is likely to be a upstream previewer issue, but I'll have to check how other previewers handle this.

**Comment by JenyaRostov** [comment]
Thank you for your suggestion. Building both Avalonia.Desktop and main Avalonia projects solved the issue
But i would like for it to work without doing that :3

**Comment by ForNeVeR** [comment]
> Building both Avalonia.Desktop and main Avalonia projects solved the issue

I can't see how it is supposed to help anything. I am very confused now.

**Comment by JenyaRostov** [comment]
You said that compiled assembly doesn't contain the method in question but after building it now does so it helps i guess?

**Comment by ForNeVeR** [comment]
How would building of `Avalonia.Desktop`, a library assembly, help you to get a method in _your_ DLL? I am genuinely confused.

**Comment by JenyaRostov** [comment]
Honestly, i have no idea. 
In my designer i have Avalonia.Desktop project chosen (from cross-platform solution), and building it after adding new event method to MainView.axaml.cs helps

https://user-images.githubusercontent.com/52300935/212055835-7be30f9f-bfbe-4cba-9338-67a15906bdf6.mp4

**Comment by ForNeVeR** [comment]
Ah, so it is not Avalonia.Desktop, but some of your libraries. Yes, this makes sense.

**Comment by ForNeVeR** [comment]
I have investigated the issue, and, yeah, it is not an AvaloniaRider problem: AvaloniaVS behaves the same.

This is because of a fundamental problem: it's impossible to apply any XAML changes that require DLL update on-the-fly.

I would recommend using MVVM command binding instead, it should work much better.

You can, of course, open an issue in [the upstream repository](https://github.com/AvaloniaUI/Avalonia/issues), but honestly I doubt it's solvable.

**Comment by ForNeVeR** [comment]
I have thought about that more, and opened #262 to track further progress.
