### ISSUE TITLE
Zoom granularity is too low in preview

### ISSUE THREAD

**Issue by 0blu** [ForNeVeR/AvaloniaRider#263]
When using CTRL+ScrollWheel the zoom level is changed too aggressively.

In this GIF I am changing the zoom level by one wheel "click".
![zooming demo](https://user-images.githubusercontent.com/7039020/216664939-f085c0d9-e49d-4a4f-995f-585109e774e1.gif)

It would be nice to have more levels of zooming available in the preview.

Tested it on Windows 10 with a scaling of 125%, AvaloniaRider v1.0.2, Rider 2022.3.2.

**Comment by ForNeVeR** [comment]
How granular would you like it to be? Something like 10% or 25% per unit (aka "click"), perhaps?

Right now it does 100% per unit, and then being coerced into range `[40%, 1000%]`: that's why one unit "out" makes it 40%, and one unit "in" makes it 200%.

**Comment by ForNeVeR** [comment]
(while we are at it, maybe we should also add a UI zoom control onto the toolbar)

**Comment by 0blu** [comment]
I would say 10% per unit.

**Comment by ForNeVeR** [comment]
I've taken a look at how Chrome handles that, and it seems they have a hardcoded set of values:
- 25%
- 33%
- 50%
- 67%
- 75%
- 80%
- 90%
- 100%
- 110%
- 125%
- 150%
- 175%
- 200%
- 250%
- 300%
- 400%
- 500%

Maybe a good idea to just do the same.

**Comment by Ch0pstix** [comment]
@ForNeVeR any update on this feature? Feature parity for the WPF previewer's zooming or at least the above mentioned solutions would be super handy.

**Comment by ForNeVeR** [comment]
No progress, yet. PRs are welcome! Though I will probably implement this myself, sooner or later.

**Comment by ScrubN** [comment]
> I've taken a look at how Chrome handles that, and it seems they have a hardcoded set of values:
> 
> * 25%
> * 33%
> * 50%
> * 67%
> * 75%
> * 80%
> * 90%
> * 100%
> * 110%
> * 125%
> * 150%
> * 175%
> * 200%
> * 250%
> * 300%
> * 400%
> * 500%
> 
> Maybe a good idea to just do the same.

The jump between 50% & 33% and 300% & 400% is a little jarring. Instead of hard coding a set of numbers that feel good because they are fractions, an algorithm can be used instead. Way back in school I wrote a crappy canvas drawing application in JS in which I used the following algorithm for converting a linear raw zoom value to an exponential zoom value.
```javascript
function calculateZoom() {
    if (rawZoom <= 0.1) // Lower clamp (far)
        rawZoom = 0.1;
    if (rawZoom >= 2.75) // Upper clamp (close)
        rawZoom = 2.75;
	
	let zoom = Math.pow(5, rawZoom - 1); // Correct zoom

    if (Math.abs(zoom - 1) < 0.05) // Clamp to 100% zoom when within 10% (for trackpads)
        zoom = 1;
		
	return zoom;
}
```
For extra context, `rawZoom` is a field held by the canvas transformer which is incremented/decremented in steps of 0.1 (or less for trackpads).
Obviously this isn't perfect as it was written by a student with a deadline but it still feels pretty good to use to me.

I do not know how zoom is currently handled internally by the plugin so I apologize if this was not helpful.

**Comment by CalvinWilkinson** [comment]
> How granular would you like it to be? Something like 10% or 25% per unit (aka "click"), perhaps?
> 
> Right now it does 100% per unit, and then being coerced into range `[40%, 1000%]`: that's why one unit "out" makes it 40%, and one unit "in" makes it 200%.

I personally think that 5-10% per unit would be great.
