### ISSUE TITLE
Does Avalonia Rider need to be updated to support Avalonia 11.1.0-rc2?

### ISSUE THREAD

**Issue by majeric** [ForNeVeR/AvaloniaRider#381]
I upgraded to prerelease in nuget but the Code-Behind isn't being respected for some reason.

**Comment by ForNeVeR** [comment]
> Does Avalonia Rider need to be updated to support Avalonia 11.1.0-rc2?

No.

> I upgraded to prerelease in nuget but the Code-Behind isn't being respected for some reason.

Please explain what is "Code-Behind" and how do you expect it to be respected. Exact steps to reproduce would be appreciated.

**Comment by majeric** [comment]
> Please explain what is "Code-Behind" and how do you expect it to be respected. Exact steps to reproduce would be appreciated.

When creating an Avalonia project the .axaml.cs files are listed in the solution as a sub-file.

- App.axaml
-- App.axaml.cs

**Comment by ForNeVeR** [comment]
> When I upgraded, it seemed to have broken that relationship and listed the .axaml.cs files seperately from the .axaml files. I wondered if it was a AvaloniaRider feature that groups them...

No, the plugin doesn't do this grouping.

It depends on two things:
1. Avalonia sets `DependentOn` somewhere in its MSBuild files.
2. The IDE visualises this by nesting the items accordingly.

If this was caused by updating Avalonia then I'd suggest investigating what's going on with the props files, and reposting to Avalonia.
